### ISSUE TITLE
RECRUIT DEVELOPERS

### ISSUE THREAD

**Issue by cbeams** [bisq-network/dao#24]
## Background

We need to grow the number of developers working on Bisq in a dedicated way. Bisq usage has been growing steadily over the 20+ months we've been live, and we're at the limits of our current dev power. There are tons of interesting and necessary features we're unable to work on because our current very small dev team is maxed out.

The problem is that, for the most part, experienced Bitcoin developers are already busy with on their own projects. This is why we need to engage in education and outreach to get _new_ Bitcoin developers involved. @jlopp [put this well](https://twitter.com/lopp/status/951529453582155776):

![image](https://user-images.githubusercontent.com/301810/34905567-86616fa2-f85b-11e7-90c5-236440bfd563.png)

This doesn't mean _brand new_ developers, necessarily. Indeed, we need experienced, professional FOSS devs to hit the ground running as much as possible with Bisq. This means bringing pros from outside Bitcoin into Bitcoin, and I think now is actually a good time to focus on this. There have to be a lot of people out there who are thinking about leaving their day jobs to get into crypto. The following is not a strict set of criteria, but rather a kind of idealized developer profile that we think it makes sense to seek out. i.e., an ideal Bisq developer candidate would be:

 - a currently employed, experienced JVM developer;
 - having experience with FOSS development, Git and GitHub;
 - having experience with and deep interest in Bitcoin as a user/holder;
 - who may or may not have done any Bitcoin development work yet, but would like to;
 - and is, possibly because of their holdings, now considering leaving their job to work in and for crypto

We've been reaching out over the last months by giving talks at conferences, doing podcast interviews and the like, but now we think it's time to try to seek out new developers in an even more focused way. So far, our outreach efforts have been primarily targeted at potential _users._ Now we want to target potential _contributors,_ and specifically _developers,_ as they are the most important missing piece right now.

## Plan

- [ ] @cbeams to write the first in what may become a series of Medium posts (#25) designed to shift the developer mindset about bitcoin exchange transactions. Right now, everybody conflates the critical activity of _acquiring_ bitcoin in the first place—which requires an exchange transaction, usually from fiat currency—with the less critical activity of _trading_ bitcoin for speculative purposes. That is, when people hear "bitcoin exchange", they tend to think of systems designed to facilitate the latter use case. Most developers aren't inspired about helping day traders trade better or faster, But many developers—the ones we want to work with, anyway—are inspired by helping people acquire and hold bitcoin, and indeed to sell it when necessary, e.g. to pay one's bills in fiat and have fiat spending cash on hand. In any case, the goal of this piece will be to get more developers thinking about exchange transactions the way we do, thinking about Bisq as a network of bridges between the fiat and Bitcoin worlds, and in turn wanting to help us realize Bisq's goals.
- [x] @mrosseel and potentially others to reach out to candidates in person at FOSDEM 2018 in February (bisq-network/events#9). The goal is to get maximum exposure for Bisq in a crowd full of FOSS developers, many of whom are JVM pros, and hopefully many of whom are Bitcoiners and would-be cypherpunks thinking about leaving their day jobs to go full-time in crypto.
- [x] @ManfredKarrer and @cbeams to put together a series of live Bisq "tech sessions" via Zoom in which we'll go deep on the technology behind Bisq, e.g. on Bisq's P2P network, trading protocol, etc. We'll publicize these sessions on Twitter, record them live, and then upload them to our YouTube channel. The goal of this series will be to show would-be Bisq developers how cool the shit we're working on is, and entice them to get involved and help make it even better.
- [ ] @cbeams to record a series of "Bisq DAO Operations" videos, in which he goes through the different tools, systems and processes we use to run the Bisq DAO, e.g. GitHub, ZenHub, Slack, the C4 process, how we vote etc. Cover the design, philosophy and goals behind our use of these tools and processes, and practical explanations about how to best interact with them. The goal of this series will be to give developers a deep sense of what it's like to work within the Bisq DAO, how it's designed for autonomy, quality, scalability, transparency, etc.

The plan above is just a sketch, and will surely evolve. The point is that we want to set out on a sustained campaign to grow Bisq's developer base. We simply cannot withstand a continued influx of users like we had in December 2017 *and* complete the implementation of the Bisq DAO with our current skeleton crew of developers. So job no. 1 for me (@cbeams) over the coming months is to do whatever it takes to get developers with the right stuff on board (note to any potential developers reading this: "on board" does not mean "hired" or "employed" by Bisq, but it does mean working on Bisq in a reasonably dedicated way and being compensated for it. You can read all about how that works [here](https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc)).

## Goals

Ultimately, the goal is to fill our open developer roles, which are also linked into this epic. (Make sure you're looking at this issue with the [ZenHub browser extension](https://zenhub.com) installed).

**Comment by mrosseel** [comment]
if no-one can make it to [Fosdem 2018](https://fosdem.org/2018/), I can tape one/more A4 with a recruitment message.

**Comment by sneurlax** [comment]
# ✋

**Comment by sneurlax** [comment]
That is to say, I'd love to help. sneurlax@gmail.com

**Comment by cbeams** [comment]
Great, @sneurlax! The best thing is to join us in Slack at https://bisq.network/slack-invite and share a bit about your expertise and interests. We can discuss and take it from there.

**Comment by ManfredKarrer** [comment]
@cbeams Great write-up! Another idea might be to make presentations at local JVM or other FOSS meetups (I did it in BCN for the JAVA meetup group and another hacker meetup).

**Comment by cbeams** [comment]
I just published a tweetstorm about this at https://twitter.com/bisq_network/status/969710515902730240.
